//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ha_wx_res_5.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ha_wx_res_5_H__
#define __WDR_ha_wx_res_5_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ha_wx_res_5_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID_TEXT = 10000;
const int REF_ID_FROM = 10001;
const int REF_ID_TO = 10002;
const int PUB_YEAR_FROM = 10003;
const int PUB_YEAR_TO = 10004;
const int IDC_SELECT_AUTH = 10005;
const int AUTHOR_FLT_TXT = 10006;
const int TITLE_WORDS_TXT = 10007;
const int IDC_JOURNAL_FLT = 10008;
const int IDC_IMPORTANCE_FLT = 10009;
const int IDC_REPRINT_FLT = 10010;
const int IDC_KEYWORDS_REFS_FLT = 10011;
const int IDC_CITED_ID = 10012;
const int IDC_CITED_IN_ID = 10013;
const int IDC_SHOW_CITING = 10014;
const int IDC_SHOW_KW = 10015;
const int IDC_SHOW_NOTES = 10016;
const int IDC_REF_OFFSET = 10017;
const int IDC_REF_LIMIT = 10018;
const int IDC_NUM_SHOWN_REFS = 10019;
const int IDC_RADIO_CRITERIA = 10020;
const int IDC_REFS_GRID = 10021;
wxSizer *bibl_refs_1_page( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_KW_ASSOCIATE = 10022;
const int IDC_KW_REMOVE_ASSOC = 10023;
const int ID_KWTREE_0 = 10024;
const int IDC_COMBO_KW_0 = 10025;
const int IDC_OBJ_TOP_0 = 10026;
const int IDC_FILTER_LEFT_0 = 10027;
const int IDC_FLT_0 = 10028;
const int IDC_FILTER_RIGHT_0 = 10029;
const int IDC_KWLIST_0 = 10030;
const int IDC_KW_TXT_0 = 10031;
const int IDC_KW_ADD_0 = 10032;
const int IDC_KW_DEL_0 = 10033;
const int IDC_COMBO_KW_1 = 10034;
const int IDC_OBJ_TOP_1 = 10035;
const int IDC_FILTER_LEFT_1 = 10036;
const int IDC_FLT_1 = 10037;
const int IDC_FILTER_RIGHT_1 = 10038;
const int IDC_KWLIST_1 = 10039;
const int IDC_KW_TXT_1 = 10040;
const int IDC_KW_ADD_1 = 10041;
const int IDC_KW_DEL_1 = 10042;
const int IDC_COMBO_KW_2 = 10043;
const int IDC_OBJ_TOP_2 = 10044;
const int IDC_FILTER_LEFT_2 = 10045;
const int IDC_FLT_2 = 10046;
const int IDC_FILTER_RIGHT_2 = 10047;
const int IDC_KWLIST_2 = 10048;
const int IDC_KW_TXT_2 = 10049;
const int IDC_KW_ADD_2 = 10050;
const int IDC_KW_DEL_2 = 10051;
const int IDC_COMBO_KW_3 = 10052;
const int IDC_OBJ_TOP_3 = 10053;
const int IDC_FILTER_LEFT_3 = 10054;
const int IDC_FLT_3 = 10055;
const int IDC_FILTER_RIGHT_3 = 10056;
const int IDC_KWLIST_3 = 10057;
const int IDC_KW_TXT_3 = 10058;
const int IDC_KW_ADD_3 = 10059;
const int IDC_KW_DEL_3 = 10060;
const int IDC_ERASE_KW1 = 10061;
const int IDC_MERGE_KW1_KW2 = 10062;
const int IDC_SET_KW2_TO_REFS_KW1 = 10063;
const int IDC_TEXT_KW1 = 10064;
const int IDC_TEXT_KW2 = 10065;
wxSizer *keywords_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_AUTH_NAME_FLT = 10066;
const int IDC_KW_AUTH_FLT = 10067;
const int IDC_SEARCH_AUTH = 10068;
const int IDC_AUTH_SET_KW = 10069;
const int IDC_AUTH_DEL_KW = 10070;
const int IDC_AUTH_BROWSE_KW = 10071;
const int IDC_AUTH_IMPORTANCE = 10072;
const int IDC_AUTH_SET_IMPORTANCE = 10073;
const int IDC_AUTH_OFFSET = 10074;
const int IDC_AUTH_LIMIT = 10075;
const int IDC_SHOW_IMPORTANCE = 10076;
const int IDC_SHOW_URL = 10077;
const int ID_CHECKBOX = 10078;
const int IDC_UPDATE_DISPLAY_OPT = 10079;
const int IDC_AUTH_GRID = 10080;
wxSizer *authors_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_CLEAN_REF_TEXT_BOX = 10081;
const int IDC_REFS_TEXT = 10082;
const int IDC_KW = 10083;
const int IDC_CITED_REF = 10084;
const int IDC_CITED_IN_REF = 10085;
const int IDC_REF_FORMAT = 10086;
const int IDC_LOAD_FROM_TEXT_BOX = 10087;
const int IDC_LOAD_FROM_FILE = 10088;
wxSizer *import_refs_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_REF_TYPE_COMBO = 10089;
const int IDC_SAVE_CHANGES = 10090;
const int IDC_DISCARD_CHANGES = 10091;
const int IDC_NEW_REF = 10092;
const int IDC_TEXT_INT_ID = 10093;
const int IDC_TEXT_EXT_ID = 10094;
const int IDC_TEXT_AUTH = 10095;
const int IDC_INCOMPLETE_AUTH = 10096;
const int IDC_TEXT_BOOK_TITLE = 10097;
const int IDC_TEXT_TITLE = 10098;
const int IDC_TEXT_JOURNAL = 10099;
const int IDC_JOURNAL_ID = 10100;
const int IDC_TEXT_YEAR = 10101;
const int IDC_TEXT_MONTH = 10102;
const int IDC_TEXT_VOL = 10103;
const int IDC_TEXT_ISS = 10104;
const int IDC_TEXT_FIRST_PAGE = 10105;
const int IDC_TEXT_LAST_PAGE = 10106;
const int IDC_TEXT_IMPORTANCE = 10107;
const int IDC_NUM_CITED_IN = 10108;
const int IDC_NUM_CITING = 10109;
const int IDC_LAST_UPDATE = 10110;
const int IDC_INT_ISI_ID = 10111;
const int IDC_EXT_ISI_ID = 10112;
const int IDC_PII_ID = 10113;
const int IDC_PUBMED_ID = 10114;
const int IDC_TEXT_DOI = 10115;
const int IDC_TEXT_URL = 10116;
const int IDC_TEXT_KEYWORDS = 10117;
const int IDC_TEXT_ABSTRACT = 10118;
const int IDC_LIST_NOTES = 10119;
wxSizer *edit_ref_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_JRN_NAME_FILTER = 10120;
const int IDC_JID_FROM = 10121;
const int IDC_JID_TO = 10122;
const int IDC_UPDATE_JRN_LIST = 10123;
const int IDC_NEW_JOURNAL = 10124;
const int IDC_JRN_GRID = 10125;
wxSizer *journals_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_FULL_NAME = 10126;
const int IDC_STD_ABBR = 10127;
const int IDC_SHORT_ABBR = 10128;
const int IDC_FNAME_ABBR = 10129;
const int IDC_ABBR_29 = 10130;
const int IDC_PUBLISHER_STR = 10131;
const int IDC_PUBLISHER_ID = 10132;
const int IDC_ISSN = 10133;
const int IDC_ESSN = 10134;
const int IDC_NLM_ID = 10135;
const int IDC_SYN_LIST = 10136;
wxSizer *jrn_edit_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_UPDATE_TOPICS = 10137;
const int ID_TREECTRL = 10138;
wxSizer *topics_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_MENU = 10139;
const int BROWSE_REFS = 10140;
const int BROWSE_KEYW = 10141;
const int BROWSE_TOPICS = 10142;
const int BROWSE_AUTH = 10143;
const int BROWSE_NOTES = 10144;
const int IDM_BROWSE_JOURNALS = 10145;
const int IDM_NEW_REF = 10146;
const int IDM_SORT_BY_AUTHOR = 10147;
const int IDM_MARK_ALL = 10148;
const int IDM_UNMARK_ALL = 10149;
const int SET_KEYW_REFS = 10150;
const int DELETE_KEYW_REFS = 10151;
const int DELETE_REFS = 10152;
const int IDM_INIT_WEBDRIVER = 10153;
const int UPDATE_WOS_IDS = 10154;
const int UPDATE_WOS_ID_REMOTE = 10155;
const int IDM_GOTO_MAIN_WOS = 10156;
const int IMPORT_WOS_FILES = 10157;
const int CLEAR_WOS_MARKED = 10158;
const int WOS_GEN_SEARCH = 10159;
const int IDM_WOS_SEARCH_PARS = 10160;
const int WOS_GO_MARKED_LIST = 10161;
const int IDC_LOAD_ALL_WWW = 10162;
const int IDC_LOAD_MARKED_WWW = 10163;
const int IDM_GS_DIALOG = 10164;
const int IDM_NEW_BROWSE_REFS_WIN = 10165;
const int IDM_PYTHON_WIN = 10166;
const int IDM_IMPORT_REFS = 10167;
wxMenuBar *bibl_db_menu();

const int IDM_MERGE_JOURNALS = 10168;
const int IDC_LOAD_JRN_LIST_1 = 10169;
const int IDC_LOAD_JRN_LIST_2 = 10170;
const int IDC_LOAD_JRN_LIST_3 = 10171;
wxMenuBar *journals_menu();

const int IDM_CURRENT_UPDATE_TIME = 10172;
wxMenuBar *edit_ref_menu();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
