//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: ha_wx_res_5.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma implementation "ha_wx_res_5_wdr.h"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "ha_wx_res_5_wdr.h"


// Euro sign hack of the year
#if wxUSE_UNICODE
    #define __WDR_EURO__ wxT("\u20ac")
#else
    #if defined(__WXMAC__)
        #define __WDR_EURO__ wxT("\xdb")
    #elif defined(__WXMSW__)
        #define __WDR_EURO__ wxT("\x80")
    #else
        #define __WDR_EURO__ wxT("\xa4")
    #endif
#endif

// Implement window functions

wxSizer *bibl_refs_1_page( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );

    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, wxT("Filters:"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->SetFont( wxFont( 14, wxROMAN, wxNORMAL, wxNORMAL ) );
    item2->Add( item3, 0, wxALIGN_CENTER, 5 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, wxT("REF_ID: From:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item6 = new wxTextCtrl( parent, REF_ID_FROM, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item6, 1, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item7 = new wxStaticText( parent, ID_TEXT, wxT("To:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item8 = new wxTextCtrl( parent, REF_ID_TO, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item4->Add( item8, 1, wxALIGN_CENTER|wxALL, 0 );

    item2->Add( item4, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT, wxT("Pub Year From:"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER, 0 );

    wxTextCtrl *item11 = new wxTextCtrl( parent, PUB_YEAR_FROM, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item9->Add( item11, 1, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item12 = new wxStaticText( parent, ID_TEXT, wxT("To:"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item13 = new wxTextCtrl( parent, PUB_YEAR_TO, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item9->Add( item13, 1, wxALIGN_CENTER, 5 );

    item2->Add( item9, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 0 );

    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item15 = new wxButton( parent, IDC_SELECT_AUTH, wxT("Select Author"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item16 = new wxTextCtrl( parent, AUTHOR_FLT_TXT, wxT(""), wxDefaultPosition, wxSize(150,-1), 0 );
    item14->Add( item16, 1, wxALIGN_CENTER|wxALL, 0 );

    item2->Add( item14, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 0 );

    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item18 = new wxStaticText( parent, ID_TEXT, wxT("Title Words:"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER, 5 );

    wxTextCtrl *item19 = new wxTextCtrl( parent, TITLE_WORDS_TXT, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item17->Add( item19, 1, wxALIGN_CENTER|wxALL, 0 );

    item2->Add( item17, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 );

    wxBoxSizer *item20 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item21 = new wxStaticText( parent, ID_TEXT, wxT("Journal:"), wxDefaultPosition, wxDefaultSize, 0 );
    item20->Add( item21, 0, wxALIGN_CENTER, 5 );

    wxTextCtrl *item22 = new wxTextCtrl( parent, IDC_JOURNAL_FLT, wxT(""), wxDefaultPosition, wxSize(100,-1), 0 );
    item20->Add( item22, 1, wxALIGN_CENTER, 5 );

    item2->Add( item20, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item23 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item24 = new wxStaticText( parent, ID_TEXT, wxT("Importance:"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item24, 0, wxALIGN_CENTER, 5 );

    wxTextCtrl *item25 = new wxTextCtrl( parent, IDC_IMPORTANCE_FLT, wxT(""), wxDefaultPosition, wxSize(50,-1), 0 );
    item23->Add( item25, 0, wxALIGN_CENTER, 0 );

    wxStaticText *item26 = new wxStaticText( parent, ID_TEXT, wxT("Reprint:"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item26, 0, wxALIGN_CENTER, 5 );

    wxTextCtrl *item27 = new wxTextCtrl( parent, IDC_REPRINT_FLT, wxT(""), wxDefaultPosition, wxSize(70,-1), 0 );
    item23->Add( item27, 0, wxALIGN_CENTER, 5 );

    item2->Add( item23, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item28 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item29 = new wxStaticText( parent, ID_TEXT, wxT("Keywords:"), wxDefaultPosition, wxDefaultSize, 0 );
    item28->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item30 = new wxTextCtrl( parent, IDC_KEYWORDS_REFS_FLT, wxT(""), wxDefaultPosition, wxSize(200,40), wxTE_MULTILINE );
    item28->Add( item30, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 0 );

    item2->Add( item28, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item31 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item32 = new wxStaticText( parent, ID_TEXT, wxT("Citing this:"), wxDefaultPosition, wxDefaultSize, 0 );
    item31->Add( item32, 0, wxALIGN_CENTER, 0 );

    wxTextCtrl *item33 = new wxTextCtrl( parent, IDC_CITED_ID, wxT(""), wxDefaultPosition, wxSize(80,70), wxTE_MULTILINE|wxHSCROLL );
    item33->SetFont( wxFont( 8, wxROMAN, wxNORMAL, wxNORMAL ) );
    item31->Add( item33, 1, wxALIGN_CENTER, 5 );

    item2->Add( item31, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item34 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item35 = new wxStaticText( parent, ID_TEXT, wxT("Cited in this:"), wxDefaultPosition, wxDefaultSize, 0 );
    item34->Add( item35, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item36 = new wxTextCtrl( parent, IDC_CITED_IN_ID, wxT(""), wxDefaultPosition, wxSize(80,70), wxTE_MULTILINE|wxHSCROLL );
    item36->SetFont( wxFont( 8, wxROMAN, wxNORMAL, wxNORMAL ) );
    item34->Add( item36, 1, wxALIGN_CENTER, 5 );

    item2->Add( item34, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item37 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item38 = new wxCheckBox( parent, IDC_SHOW_CITING, wxT("Show Citing"), wxDefaultPosition, wxDefaultSize, 0 );
    item37->Add( item38, 0, wxALIGN_CENTER, 5 );

    wxCheckBox *item39 = new wxCheckBox( parent, IDC_SHOW_KW, wxT("Show Keywords"), wxDefaultPosition, wxDefaultSize, 0 );
    item37->Add( item39, 0, wxALIGN_CENTER, 5 );

    wxCheckBox *item40 = new wxCheckBox( parent, IDC_SHOW_NOTES, wxT("Show Notes"), wxDefaultPosition, wxDefaultSize, 0 );
    item37->Add( item40, 0, wxALIGN_CENTER, 5 );

    item2->Add( item37, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item41 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item42 = new wxStaticText( parent, ID_TEXT, wxT("Ref Offset:"), wxDefaultPosition, wxDefaultSize, 0 );
    item41->Add( item42, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item43 = new wxTextCtrl( parent, IDC_REF_OFFSET, wxT(""), wxDefaultPosition, wxSize(40,-1), 0 );
    item41->Add( item43, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item44 = new wxStaticText( parent, ID_TEXT, wxT("Limit:"), wxDefaultPosition, wxDefaultSize, 0 );
    item41->Add( item44, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item45 = new wxTextCtrl( parent, IDC_REF_LIMIT, wxT(""), wxDefaultPosition, wxSize(40,-1), 0 );
    item41->Add( item45, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item46 = new wxStaticText( parent, ID_TEXT, wxT("Shown:"), wxDefaultPosition, wxDefaultSize, 0 );
    item41->Add( item46, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item47 = new wxTextCtrl( parent, IDC_NUM_SHOWN_REFS, wxT(""), wxDefaultPosition, wxSize(40,-1), wxTE_READONLY );
    item41->Add( item47, 0, wxALIGN_CENTER|wxALL, 0 );

    item2->Add( item41, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item48 = new wxBoxSizer( wxHORIZONTAL );

    wxString strs49[] = 
    {
        wxT("Marked"), 
        wxT("Filtered"), 
        wxT("All")
    };
    wxRadioBox *item49 = new wxRadioBox( parent, IDC_RADIO_CRITERIA, wxT("References Action Applied to:"), wxDefaultPosition, wxSize(-1,40), 3, strs49, 1, wxRA_SPECIFY_ROWS );
    item48->Add( item49, 0, wxGROW|wxALL|wxSHAPED, 0 );

    item2->Add( item48, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxBoxSizer *item50 = new wxBoxSizer( wxVERTICAL );

    wxGrid *item51 = new wxGrid( parent, IDC_REFS_GRID, wxDefaultPosition, wxSize(850,450), wxWANTS_CHARS );
    item51->CreateGrid( 10, 9, wxGrid::wxGridSelectRows );
    item50->Add( item51, 1, wxGROW|wxALL, 5 );

    item1->Add( item50, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item0->Add( item1, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *keywords_dlg( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxStaticText *item1 = new wxStaticText( parent, ID_TEXT, wxT("Object Association"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE );
    item1->SetFont( wxFont( 14, wxROMAN, wxNORMAL, wxBOLD ) );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item3 = new wxButton( parent, IDC_KW_ASSOCIATE, wxT("Associate Selected Objects"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, IDC_KW_REMOVE_ASSOC, wxT("Remove Association of Selected Objects"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item6 = new wxBoxSizer( wxVERTICAL );

    wxTreeCtrl *item7 = new wxTreeCtrl( parent, ID_KWTREE_0, wxDefaultPosition, wxSize(120,160), wxTR_MULTIPLE|wxTR_HAS_BUTTONS|wxTR_EDIT_LABELS|wxTR_LINES_AT_ROOT|wxSUNKEN_BORDER|wxTR_HIDE_ROOT );
    item6->Add( item7, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item5->Add( item6, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxVERTICAL );

    item5->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxVERTICAL );

    wxString *strs10 = (wxString*) NULL;
    wxComboBox *item10 = new wxComboBox( parent, IDC_COMBO_KW_0, wxT(""), wxDefaultPosition, wxSize(100,-1), 0, strs10, wxCB_DROPDOWN );
    item10->SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) );
    item9->Add( item10, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item11 = new wxTextCtrl( parent, IDC_OBJ_TOP_0, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item9->Add( item11, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item13 = new wxCheckBox( parent, IDC_FILTER_LEFT_0, wxT("FLT LEFT"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item13, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item14 = new wxCheckBox( parent, IDC_FLT_0, wxT("FLT"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item14, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item15 = new wxCheckBox( parent, IDC_FILTER_RIGHT_0, wxT("FLT RIGHT"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item15, 1, wxALIGN_CENTER|wxALL, 5 );

    item9->Add( item12, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxListCtrl *item16 = new wxListCtrl( parent, IDC_KWLIST_0, wxDefaultPosition, wxSize(160,300), wxLC_LIST|wxSUNKEN_BORDER );
    item9->Add( item16, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item17 = new wxTextCtrl( parent, IDC_KW_TXT_0, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item9->Add( item17, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item19 = new wxButton( parent, IDC_KW_ADD_0, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item20 = new wxButton( parent, IDC_KW_DEL_0, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    item9->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    item5->Add( item9, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 0 );

    wxBoxSizer *item21 = new wxBoxSizer( wxVERTICAL );

    wxString *strs22 = (wxString*) NULL;
    wxComboBox *item22 = new wxComboBox( parent, IDC_COMBO_KW_1, wxT(""), wxDefaultPosition, wxSize(100,-1), 0, strs22, wxCB_DROPDOWN );
    item22->SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) );
    item21->Add( item22, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item23 = new wxTextCtrl( parent, IDC_OBJ_TOP_1, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item21->Add( item23, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item24 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item25 = new wxCheckBox( parent, IDC_FILTER_LEFT_1, wxT("FLT LEFT"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item25, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item26 = new wxCheckBox( parent, IDC_FLT_1, wxT("FLT"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item26, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item27 = new wxCheckBox( parent, IDC_FILTER_RIGHT_1, wxT("FLT RIGHT"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item27, 1, wxALIGN_CENTER|wxALL, 5 );

    item21->Add( item24, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxListCtrl *item28 = new wxListCtrl( parent, IDC_KWLIST_1, wxDefaultPosition, wxSize(160,300), wxLC_LIST|wxSUNKEN_BORDER );
    item21->Add( item28, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item29 = new wxTextCtrl( parent, IDC_KW_TXT_1, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item21->Add( item29, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item30 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item31 = new wxButton( parent, IDC_KW_ADD_1, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item30->Add( item31, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item32 = new wxButton( parent, IDC_KW_DEL_1, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item30->Add( item32, 0, wxALIGN_CENTER|wxALL, 5 );

    item21->Add( item30, 0, wxALIGN_CENTER|wxALL, 5 );

    item5->Add( item21, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 0 );

    wxBoxSizer *item33 = new wxBoxSizer( wxVERTICAL );

    wxString *strs34 = (wxString*) NULL;
    wxComboBox *item34 = new wxComboBox( parent, IDC_COMBO_KW_2, wxT(""), wxDefaultPosition, wxSize(100,-1), 0, strs34, wxCB_DROPDOWN );
    item34->SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) );
    item33->Add( item34, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item35 = new wxTextCtrl( parent, IDC_OBJ_TOP_2, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item33->Add( item35, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item36 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item37 = new wxCheckBox( parent, IDC_FILTER_LEFT_2, wxT("FLT LEFT"), wxDefaultPosition, wxDefaultSize, 0 );
    item36->Add( item37, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item38 = new wxCheckBox( parent, IDC_FLT_2, wxT("FLT"), wxDefaultPosition, wxDefaultSize, 0 );
    item36->Add( item38, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item39 = new wxCheckBox( parent, IDC_FILTER_RIGHT_2, wxT("FLT RIGHT"), wxDefaultPosition, wxDefaultSize, 0 );
    item36->Add( item39, 1, wxALIGN_CENTER|wxALL, 5 );

    item33->Add( item36, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxListCtrl *item40 = new wxListCtrl( parent, IDC_KWLIST_2, wxDefaultPosition, wxSize(160,300), wxLC_LIST|wxSUNKEN_BORDER );
    item33->Add( item40, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item41 = new wxTextCtrl( parent, IDC_KW_TXT_2, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item33->Add( item41, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item42 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item43 = new wxButton( parent, IDC_KW_ADD_2, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item42->Add( item43, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item44 = new wxButton( parent, IDC_KW_DEL_2, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item42->Add( item44, 0, wxALIGN_CENTER|wxALL, 5 );

    item33->Add( item42, 0, wxALIGN_CENTER|wxALL, 5 );

    item5->Add( item33, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 0 );

    wxBoxSizer *item45 = new wxBoxSizer( wxVERTICAL );

    wxString *strs46 = (wxString*) NULL;
    wxComboBox *item46 = new wxComboBox( parent, IDC_COMBO_KW_3, wxT(""), wxDefaultPosition, wxSize(100,-1), 0, strs46, wxCB_DROPDOWN );
    item46->SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) );
    item45->Add( item46, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item47 = new wxTextCtrl( parent, IDC_OBJ_TOP_3, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item45->Add( item47, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item48 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item49 = new wxCheckBox( parent, IDC_FILTER_LEFT_3, wxT("FLT LEFT"), wxDefaultPosition, wxDefaultSize, 0 );
    item48->Add( item49, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item50 = new wxCheckBox( parent, IDC_FLT_3, wxT("FLT"), wxDefaultPosition, wxDefaultSize, 0 );
    item48->Add( item50, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item51 = new wxCheckBox( parent, IDC_FILTER_RIGHT_3, wxT("FLT RIGHT"), wxDefaultPosition, wxDefaultSize, 0 );
    item48->Add( item51, 1, wxALIGN_CENTER|wxALL, 5 );

    item45->Add( item48, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxListCtrl *item52 = new wxListCtrl( parent, IDC_KWLIST_3, wxDefaultPosition, wxSize(160,300), wxLC_LIST|wxSUNKEN_BORDER );
    item45->Add( item52, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item53 = new wxTextCtrl( parent, IDC_KW_TXT_3, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item45->Add( item53, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item54 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item55 = new wxButton( parent, IDC_KW_ADD_3, wxT("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item54->Add( item55, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item56 = new wxButton( parent, IDC_KW_DEL_3, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item54->Add( item56, 0, wxALIGN_CENTER|wxALL, 5 );

    item45->Add( item54, 0, wxALIGN_CENTER|wxALL, 5 );

    item5->Add( item45, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 0 );

    item0->Add( item5, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item57 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item58 = new wxBoxSizer( wxVERTICAL );

    wxButton *item59 = new wxButton( parent, IDC_ERASE_KW1, wxT("Erase KW1"), wxDefaultPosition, wxDefaultSize, 0 );
    item58->Add( item59, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item60 = new wxButton( parent, IDC_MERGE_KW1_KW2, wxT("Merge KW1 to KW2"), wxDefaultPosition, wxDefaultSize, 0 );
    item58->Add( item60, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item61 = new wxButton( parent, IDC_SET_KW2_TO_REFS_KW1, wxT("SET KW2 TO REFS OF KW1"), wxDefaultPosition, wxDefaultSize, 0 );
    item58->Add( item61, 0, wxALIGN_CENTER|wxALL, 5 );

    item57->Add( item58, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item62 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item63 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item64 = new wxStaticText( parent, ID_TEXT, wxT("KW1"), wxDefaultPosition, wxDefaultSize, 0 );
    item63->Add( item64, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item65 = new wxTextCtrl( parent, IDC_TEXT_KW1, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item63->Add( item65, 0, wxALIGN_CENTER|wxALL, 5 );

    item62->Add( item63, 0, wxALIGN_CENTER|wxALL, 0 );

    wxBoxSizer *item66 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item67 = new wxStaticText( parent, ID_TEXT, wxT("KW2"), wxDefaultPosition, wxDefaultSize, 0 );
    item66->Add( item67, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item68 = new wxTextCtrl( parent, IDC_TEXT_KW2, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item66->Add( item68, 0, wxALIGN_CENTER|wxALL, 5 );

    item62->Add( item66, 0, wxALIGN_CENTER|wxALL, 0 );

    item57->Add( item62, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item57, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *authors_dlg( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );

    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, wxT("Filter:"), wxDefaultPosition, wxDefaultSize, 0 );
    item3->SetFont( wxFont( 14, wxROMAN, wxNORMAL, wxNORMAL ) );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, wxT("Name Filter:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item6 = new wxTextCtrl( parent, IDC_AUTH_NAME_FLT, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item4->Add( item6, 1, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item4, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT, wxT("Keywords:"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item9 = new wxTextCtrl( parent, IDC_KW_AUTH_FLT, wxT(""), wxDefaultPosition, wxSize(300,40), wxTE_MULTILINE );
    item7->Add( item9, 1, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item11 = new wxButton( parent, IDC_SEARCH_AUTH, wxT("Search Authors"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item12 = new wxButton( parent, IDC_AUTH_SET_KW, wxT("Set KW to Marked"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item13 = new wxButton( parent, IDC_AUTH_DEL_KW, wxT("Del KW Marked"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item14 = new wxButton( parent, IDC_AUTH_BROWSE_KW, wxT("Browse KW"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item15 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item16 = new wxStaticText( parent, ID_TEXT, wxT("Importance"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item17 = new wxTextCtrl( parent, IDC_AUTH_IMPORTANCE, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item15->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item18 = new wxButton( parent, IDC_AUTH_SET_IMPORTANCE, wxT("Set Importance Marked"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item15, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item20 = new wxStaticText( parent, ID_TEXT, wxT("Offset:"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item21 = new wxTextCtrl( parent, IDC_AUTH_OFFSET, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item19->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item22 = new wxStaticText( parent, ID_TEXT, wxT("Limit:"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item23 = new wxTextCtrl( parent, IDC_AUTH_LIMIT, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item19->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item19, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    item1->Add( item2, 1, wxALIGN_CENTER|wxALL, 0 );

    wxBoxSizer *item24 = new wxBoxSizer( wxVERTICAL );

    wxStaticText *item25 = new wxStaticText( parent, ID_TEXT, wxT("Display options:"), wxDefaultPosition, wxDefaultSize, 0 );
    item25->SetFont( wxFont( 14, wxROMAN, wxNORMAL, wxNORMAL ) );
    item24->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item26 = new wxCheckBox( parent, IDC_SHOW_IMPORTANCE, wxT("Show Importance"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item26, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item27 = new wxCheckBox( parent, IDC_SHOW_KW, wxT("Show Keywords"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item27, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item28 = new wxCheckBox( parent, IDC_SHOW_URL, wxT("Show URL"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item28, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item29 = new wxCheckBox( parent, IDC_SHOW_NOTES, wxT("Show Notes"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item29, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item30 = new wxCheckBox( parent, ID_CHECKBOX, wxT("Check"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item30, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item31 = new wxCheckBox( parent, ID_CHECKBOX, wxT("Check"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item31, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item32 = new wxButton( parent, IDC_UPDATE_DISPLAY_OPT, wxT("Update Display Options"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->Add( item32, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item24, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 0 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item33 = new wxBoxSizer( wxHORIZONTAL );

    wxGrid *item34 = new wxGrid( parent, IDC_AUTH_GRID, wxDefaultPosition, wxSize(610,200), wxWANTS_CHARS );
    item34->CreateGrid( 10, 5, wxGrid::wxGridSelectCells );
    item33->Add( item34, 1, wxGROW|wxALL, 5 );

    item0->Add( item33, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *import_refs_dlg( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("References Text:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 1, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item3 = new wxButton( parent, IDC_CLEAN_REF_TEXT_BOX, wxT("Clean Refs Text Box"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item4 = new wxTextCtrl( parent, IDC_REFS_TEXT, wxT(""), wxDefaultPosition, wxSize(600,400), wxTE_MULTILINE );
    item0->Add( item4, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, wxT("Assign Key Words:"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item6 = new wxTextCtrl( parent, IDC_KW, wxT(""), wxDefaultPosition, wxSize(80,40), wxTE_MULTILINE );
    item0->Add( item6, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT, wxT("Citing this:"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item9 = new wxTextCtrl( parent, IDC_CITED_REF, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT, wxT("Cited in this:"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item11 = new wxTextCtrl( parent, IDC_CITED_IN_REF, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );

    wxString strs13[] = 
    {
        wxT("PubMed XML"), 
        wxT("ISI"), 
        wxT("RIS"), 
        wxT("BibTeX"), 
        wxT("NBIB")
    };
    wxRadioBox *item13 = new wxRadioBox( parent, IDC_REF_FORMAT, wxT("Format"), wxDefaultPosition, wxDefaultSize, 5, strs13, 1, wxRA_SPECIFY_ROWS );
    item12->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item12, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item15 = new wxButton( parent, IDC_LOAD_FROM_TEXT_BOX, wxT("Load From Text Box"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 1, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item16 = new wxButton( parent, IDC_LOAD_FROM_FILE, wxT("Load From File"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item16, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item14, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *edit_ref_dlg( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Ref Type:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxString strs3[] = 
    {
        wxT("Journal Article"), 
        wxT("In Series"), 
        wxT("Book"), 
        wxT("Book Chapter")
    };
    wxComboBox *item3 = new wxComboBox( parent, IDC_REF_TYPE_COMBO, wxT(""), wxDefaultPosition, wxSize(160,-1), 4, strs3, wxCB_DROPDOWN );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, IDC_SAVE_CHANGES, wxT("Save Changes"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item5 = new wxButton( parent, IDC_DISCARD_CHANGES, wxT("Discard Changes"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item6 = new wxButton( parent, IDC_NEW_REF, wxT("New Reference"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT, wxT("Internal ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item9 = new wxTextCtrl( parent, IDC_TEXT_INT_ID, wxT(""), wxDefaultPosition, wxSize(60,-1), wxTE_READONLY );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT, wxT("External ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item11 = new wxTextCtrl( parent, IDC_TEXT_EXT_ID, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item7->Add( item11, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item13 = new wxStaticText( parent, ID_TEXT, wxT("Authors:"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item14 = new wxTextCtrl( parent, IDC_TEXT_AUTH, wxT(""), wxDefaultPosition, wxSize(400,50), wxTE_MULTILINE );
    item12->Add( item14, 1, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item15 = new wxCheckBox( parent, IDC_INCOMPLETE_AUTH, wxT("Incomplete"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item12, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item16 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item17 = new wxStaticText( parent, ID_TEXT, wxT("Book Title:"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item17, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item18 = new wxTextCtrl( parent, IDC_TEXT_BOOK_TITLE, wxT(""), wxDefaultPosition, wxSize(80,40), wxTE_MULTILINE );
    item16->Add( item18, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item16, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item20 = new wxStaticText( parent, ID_TEXT, wxT("Title:"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item21 = new wxTextCtrl( parent, IDC_TEXT_TITLE, wxT(""), wxDefaultPosition, wxSize(420,50), wxTE_MULTILINE );
    item19->Add( item21, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item19, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item22 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item23 = new wxStaticText( parent, ID_TEXT, wxT("Journal:"), wxDefaultPosition, wxDefaultSize, 0 );
    item22->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item24 = new wxTextCtrl( parent, IDC_TEXT_JOURNAL, wxT(""), wxDefaultPosition, wxSize(400,-1), 0 );
    item22->Add( item24, 1, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item25 = new wxStaticText( parent, ID_TEXT, wxT("jid:"), wxDefaultPosition, wxDefaultSize, 0 );
    item22->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item26 = new wxTextCtrl( parent, IDC_JOURNAL_ID, wxT(""), wxDefaultPosition, wxSize(50,-1), 0 );
    item22->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item22, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item27 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item28 = new wxStaticText( parent, ID_TEXT, wxT("Year:"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item28, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item29 = new wxTextCtrl( parent, IDC_TEXT_YEAR, wxT(""), wxDefaultPosition, wxSize(40,-1), 0 );
    item27->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item30 = new wxStaticText( parent, ID_TEXT, wxT("Month:"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item30, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item31 = new wxTextCtrl( parent, IDC_TEXT_MONTH, wxT(""), wxDefaultPosition, wxSize(50,-1), 0 );
    item27->Add( item31, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item32 = new wxStaticText( parent, ID_TEXT, wxT("Volume:"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item32, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item33 = new wxTextCtrl( parent, IDC_TEXT_VOL, wxT(""), wxDefaultPosition, wxSize(40,-1), 0 );
    item27->Add( item33, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item34 = new wxStaticText( parent, ID_TEXT, wxT("Issue:"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item34, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item35 = new wxTextCtrl( parent, IDC_TEXT_ISS, wxT(""), wxDefaultPosition, wxSize(40,-1), 0 );
    item27->Add( item35, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item36 = new wxStaticText( parent, ID_TEXT, wxT("Pages:"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item36, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item37 = new wxTextCtrl( parent, IDC_TEXT_FIRST_PAGE, wxT(""), wxDefaultPosition, wxSize(60,-1), 0 );
    item27->Add( item37, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item38 = new wxStaticText( parent, ID_TEXT, wxT("-"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item38, 0, wxALIGN_CENTER|wxALL, 0 );

    wxTextCtrl *item39 = new wxTextCtrl( parent, IDC_TEXT_LAST_PAGE, wxT(""), wxDefaultPosition, wxSize(60,-1), 0 );
    item27->Add( item39, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item27, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item40 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item41 = new wxStaticText( parent, ID_TEXT, wxT("Importance:"), wxDefaultPosition, wxDefaultSize, 0 );
    item40->Add( item41, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item42 = new wxTextCtrl( parent, IDC_TEXT_IMPORTANCE, wxT(""), wxDefaultPosition, wxSize(30,-1), 0 );
    item40->Add( item42, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item43 = new wxStaticText( parent, ID_TEXT, wxT("Cited in this:"), wxDefaultPosition, wxDefaultSize, 0 );
    item40->Add( item43, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item44 = new wxTextCtrl( parent, IDC_NUM_CITED_IN, wxT(""), wxDefaultPosition, wxSize(40,-1), 0 );
    item40->Add( item44, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item45 = new wxStaticText( parent, ID_TEXT, wxT("Citing this:"), wxDefaultPosition, wxDefaultSize, 0 );
    item40->Add( item45, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item46 = new wxTextCtrl( parent, IDC_NUM_CITING, wxT(""), wxDefaultPosition, wxSize(40,-1), 0 );
    item40->Add( item46, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item47 = new wxStaticText( parent, ID_TEXT, wxT("Last Update:"), wxDefaultPosition, wxDefaultSize, 0 );
    item40->Add( item47, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item48 = new wxTextCtrl( parent, IDC_LAST_UPDATE, wxT(""), wxDefaultPosition, wxSize(100,-1), 0 );
    item40->Add( item48, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item40, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item49 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item50 = new wxStaticText( parent, ID_TEXT, wxT("ISI ID Int:"), wxDefaultPosition, wxDefaultSize, 0 );
    item49->Add( item50, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item51 = new wxTextCtrl( parent, IDC_INT_ISI_ID, wxT(""), wxDefaultPosition, wxSize(100,-1), 0 );
    item49->Add( item51, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item52 = new wxStaticText( parent, ID_TEXT, wxT("ISI ID Ext:"), wxDefaultPosition, wxDefaultSize, 0 );
    item49->Add( item52, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item53 = new wxTextCtrl( parent, IDC_EXT_ISI_ID, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item49->Add( item53, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item54 = new wxStaticText( parent, ID_TEXT, wxT("PII ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item49->Add( item54, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item55 = new wxTextCtrl( parent, IDC_PII_ID, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item49->Add( item55, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item49, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item56 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item57 = new wxStaticText( parent, ID_TEXT, wxT("PubMed ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item56->Add( item57, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item58 = new wxTextCtrl( parent, IDC_PUBMED_ID, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item56->Add( item58, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item59 = new wxStaticText( parent, ID_TEXT, wxT("DOI:"), wxDefaultPosition, wxDefaultSize, 0 );
    item56->Add( item59, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item60 = new wxTextCtrl( parent, IDC_TEXT_DOI, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item56->Add( item60, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item56, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item61 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item62 = new wxStaticText( parent, ID_TEXT, wxT("URL:"), wxDefaultPosition, wxDefaultSize, 0 );
    item61->Add( item62, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item63 = new wxTextCtrl( parent, IDC_TEXT_URL, wxT(""), wxDefaultPosition, wxSize(390,-1), 0 );
    item61->Add( item63, 1, wxALIGN_CENTER|wxALL, 0 );

    item0->Add( item61, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item64 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item65 = new wxStaticText( parent, ID_TEXT, wxT("Key Words:"), wxDefaultPosition, wxDefaultSize, 0 );
    item64->Add( item65, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item66 = new wxTextCtrl( parent, IDC_TEXT_KEYWORDS, wxT(""), wxDefaultPosition, wxSize(380,50), wxTE_MULTILINE );
    item64->Add( item66, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item0->Add( item64, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item67 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item68 = new wxStaticText( parent, ID_TEXT, wxT("Abstract:"), wxDefaultPosition, wxDefaultSize, 0 );
    item67->Add( item68, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item69 = new wxTextCtrl( parent, IDC_TEXT_ABSTRACT, wxT(""), wxDefaultPosition, wxSize(390,80), wxTE_MULTILINE );
    item67->Add( item69, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item67, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item70 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item71 = new wxStaticText( parent, ID_TEXT, wxT("Notes:"), wxDefaultPosition, wxDefaultSize, 0 );
    item70->Add( item71, 0, wxALIGN_CENTER|wxALL, 5 );

    wxListCtrl *item72 = new wxListCtrl( parent, IDC_LIST_NOTES, wxDefaultPosition, wxSize(160,40), wxLC_SMALL_ICON|wxSUNKEN_BORDER );
    item70->Add( item72, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item70, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *journals_dlg( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Journal Name Filter:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, IDC_JRN_NAME_FILTER, wxT(""), wxDefaultPosition, wxSize(500,-1), 0 );
    item1->Add( item3, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, wxT("Journal ID: From:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item6 = new wxTextCtrl( parent, IDC_JID_FROM, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item7 = new wxStaticText( parent, ID_TEXT, wxT("To:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item8 = new wxTextCtrl( parent, IDC_JID_TO, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item4->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item10 = new wxButton( parent, IDC_UPDATE_JRN_LIST, wxT("Update Journal List"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 0 );

    wxButton *item11 = new wxButton( parent, IDC_NEW_JOURNAL, wxT("New Journal"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item9, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );

    wxGrid *item13 = new wxGrid( parent, IDC_JRN_GRID, wxDefaultPosition, wxSize(450,200), wxWANTS_CHARS );
    item13->CreateGrid( 10, 2, wxGrid::wxGridSelectRows );
    item12->Add( item13, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item0->Add( item12, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *jrn_edit_dlg( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Journal ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, IDC_JOURNAL_ID, wxT(""), wxDefaultPosition, wxSize(50,-1), wxTE_READONLY );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 0 );

    wxButton *item4 = new wxButton( parent, IDC_SAVE_CHANGES, wxT("Save Changes"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item5 = new wxButton( parent, IDC_DISCARD_CHANGES, wxT("Discard Changes"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item6 = new wxButton( parent, IDC_NEW_JOURNAL, wxT("New Journal"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT, wxT("Full Name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item9 = new wxTextCtrl( parent, IDC_FULL_NAME, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->Add( item9, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item11 = new wxStaticText( parent, ID_TEXT, wxT("Standard Abbreviation:"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item12 = new wxTextCtrl( parent, IDC_STD_ABBR, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item10->Add( item12, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item10, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item14 = new wxStaticText( parent, ID_TEXT, wxT("Short Abbreviation:"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item15 = new wxTextCtrl( parent, IDC_SHORT_ABBR, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item13->Add( item15, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item13, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item16 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item17 = new wxStaticText( parent, ID_TEXT, wxT("File Name Abbreviation:"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item18 = new wxTextCtrl( parent, IDC_FNAME_ABBR, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item16->Add( item18, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item16, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item20 = new wxStaticText( parent, ID_TEXT, wxT("29 Symbol abbreviation:"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item21 = new wxTextCtrl( parent, IDC_ABBR_29, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item19->Add( item21, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item19, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item22 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item23 = new wxStaticText( parent, ID_TEXT, wxT("Publisher:"), wxDefaultPosition, wxDefaultSize, 0 );
    item22->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item24 = new wxTextCtrl( parent, IDC_PUBLISHER_STR, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item22->Add( item24, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item22, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item25 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item26 = new wxStaticText( parent, ID_TEXT, wxT("Publisher ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item25->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item27 = new wxTextCtrl( parent, IDC_PUBLISHER_ID, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item25->Add( item27, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item25, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item28 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item29 = new wxStaticText( parent, ID_TEXT, wxT("ISSN:"), wxDefaultPosition, wxDefaultSize, 0 );
    item28->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item30 = new wxTextCtrl( parent, IDC_ISSN, wxT(""), wxDefaultPosition, wxSize(100,-1), 0 );
    item28->Add( item30, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item31 = new wxStaticText( parent, ID_TEXT, wxT("ESSN:"), wxDefaultPosition, wxDefaultSize, 0 );
    item28->Add( item31, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item32 = new wxTextCtrl( parent, IDC_ESSN, wxT(""), wxDefaultPosition, wxSize(100,-1), 0 );
    item28->Add( item32, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item33 = new wxStaticText( parent, ID_TEXT, wxT("NLM ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item28->Add( item33, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item34 = new wxTextCtrl( parent, IDC_NLM_ID, wxT(""), wxDefaultPosition, wxSize(120,-1), 0 );
    item28->Add( item34, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item28, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item35 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item36 = new wxStaticText( parent, ID_TEXT, wxT("Synonyms:"), wxDefaultPosition, wxDefaultSize, 0 );
    item35->Add( item36, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item37 = new wxTextCtrl( parent, IDC_SYN_LIST, wxT(""), wxDefaultPosition, wxSize(80,100), wxTE_MULTILINE );
    item35->Add( item37, 1, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item0->Add( item35, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *topics_dlg( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item2 = new wxButton( parent, IDC_UPDATE_TOPICS, wxT("Update Topics"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item3 = new wxBoxSizer( wxHORIZONTAL );

    wxTreeCtrl *item4 = new wxTreeCtrl( parent, ID_TREECTRL, wxDefaultPosition, wxSize(120,160), wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT|wxSUNKEN_BORDER );
    item3->Add( item4, 1, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

// Implement menubar functions

wxMenuBar *bibl_db_menu()
{
    wxMenuBar *item0 = new wxMenuBar;
    
    wxMenu* item1 = new wxMenu;
    item1->Append( BROWSE_REFS, wxT("Browse References"), wxT("") );
    item1->Append( BROWSE_KEYW, wxT("Browse Keywords"), wxT("") );
    item1->Append( BROWSE_TOPICS, wxT("Browse Topics"), wxT("") );
    item1->Append( BROWSE_AUTH, wxT("Browse Authors"), wxT("") );
    item1->Append( BROWSE_NOTES, wxT("Browse Notes"), wxT("") );
    item1->Append( IDM_BROWSE_JOURNALS, wxT("Browse Journals"), wxT("") );
    item0->Append( item1, wxT("Actions") );
    
    wxMenu* item2 = new wxMenu;
    item2->Append( IDM_NEW_REF, wxT("New Reference"), wxT("") );
    item2->Append( IDM_SORT_BY_AUTHOR, wxT("Sort Refs By Author"), wxT("") );
    item2->Append( IDM_MARK_ALL, wxT("Mark All Filtered Refs"), wxT("") );
    item2->Append( IDM_UNMARK_ALL, wxT("UnMark All Filtered References"), wxT("") );
    item2->Append( SET_KEYW_REFS, wxT("Set Keywords to Marked Refs"), wxT("") );
    item2->Append( DELETE_KEYW_REFS, wxT("Delete Keywords from Marked Refs"), wxT("") );
    item2->Append( DELETE_REFS, wxT("Delete Marked References"), wxT("") );
    item0->Append( item2, wxT("Edit ") );
    
    wxMenu* item3 = new wxMenu;
    item3->Append( IDM_INIT_WEBDRIVER, wxT("Init Webdriver"), wxT("") );
    item3->Append( UPDATE_WOS_IDS, wxT("Update Web of Science Session IDs"), wxT("") );
    item3->Append( UPDATE_WOS_ID_REMOTE, wxT("Update WOS IDs Remote Access  "), wxT("") );
    item3->Append( IDM_GOTO_MAIN_WOS, wxT("Go to Main WOS Page"), wxT("") );
    item3->Append( IMPORT_WOS_FILES, wxT("Import References from WOS file"), wxT("") );
    item3->Append( CLEAR_WOS_MARKED, wxT("Clear WOS Marked"), wxT("") );
    item3->Append( WOS_GEN_SEARCH, wxT("WOS General Search"), wxT("") );
    item3->Append( IDM_WOS_SEARCH_PARS, wxT("WOS Search Current Params"), wxT("") );
    item3->Append( WOS_GO_MARKED_LIST, wxT("Go WOS marked list"), wxT("") );
    item0->Append( item3, wxT("Web of Science") );
    
    wxMenu* item4 = new wxMenu;
    item4->Append( IDC_LOAD_ALL_WWW, wxT("Load all displayed refs from WWW"), wxT("") );
    item4->Append( IDC_LOAD_MARKED_WWW, wxT("Load Marked refs from WWW"), wxT("") );
    item4->Append( IDM_GS_DIALOG, wxT("Open Google Scholar Dialog"), wxT("") );
    item0->Append( item4, wxT("WWW bibl") );
    
    wxMenu* item5 = new wxMenu;
    item5->Append( IDM_NEW_BROWSE_REFS_WIN, wxT("New Browse Refs Window"), wxT("") );
    item5->Append( IDM_PYTHON_WIN, wxT("New Python Window"), wxT("") );
    item0->Append( item5, wxT("Window") );
    
    wxMenu* item6 = new wxMenu;
    item6->Append( IDM_IMPORT_REFS, wxT("Import References"), wxT("") );
    item0->Append( item6, wxT("Import/Export") );
    
    return item0;
}

wxMenuBar *journals_menu()
{
    wxMenuBar *item0 = new wxMenuBar;
    
    wxMenu* item1 = new wxMenu;
    item1->Append( IDM_MERGE_JOURNALS, wxT("Merge Journals (From -> To)"), wxT("") );
    item0->Append( item1, wxT("Actions") );
    
    wxMenu* item2 = new wxMenu;
    item2->Append( IDC_LOAD_JRN_LIST_1, wxT("Load Journal List 1"), wxT("") );
    item2->Append( IDC_LOAD_JRN_LIST_2, wxT("Load Journal List 2"), wxT("") );
    item2->Append( IDC_LOAD_JRN_LIST_3, wxT("Load Journal List 3"), wxT("") );
    item0->Append( item2, wxT("AXX") );
    
    return item0;
}

wxMenuBar *edit_ref_menu()
{
    wxMenuBar *item0 = new wxMenuBar;
    
    wxMenu* item1 = new wxMenu;
    item1->Append( IDM_CURRENT_UPDATE_TIME, wxT("Set Ref Update Time to Current"), wxT("") );
    item0->Append( item1, wxT("Actions") );
    
    return item0;
}

// Implement toolbar functions

// Implement bitmap functions


// End of generated file
