use igor_bibl_db;
SELECT count(id2) FROM OBJ_ASSOC INNER JOIN OBJECTS ON OBJ_ASSOC.id2 = OBJECTS.id AND OBJECTS.type in (4,2) 
WHERE (id2 in ( SELECT ID2 FROM (
SELECT id2 FROM OBJ_ASSOC WHERE id1 in(476036) 
UNION 
SELECT id1 FROM OBJ_ASSOC WHERE id2 in(476036) 
) AS SEL_ID )) 


use igor_bibl_db;
select count(id) FROM (
SELECT id2 AS id FROM OBJ_ASSOC WHERE id1 in(476036) 
UNION 
SELECT id1 FROM OBJ_ASSOC WHERE id2 in(476036) 
) AS SEL_ID

use igor_bibl_db;
SELECT id2   FROM OBJ_ASSOC INNER JOIN OBJECTS ON OBJ_ASSOC.id2 = OBJECTS.id 
WHERE  (
id2 in ( SELECT ID2 FROM (
SELECT id2 FROM OBJ_ASSOC WHERE id1 in(476036) 
UNION 
SELECT id1 FROM OBJ_ASSOC WHERE id2 in(476036)
) AS ID_NDIR ) 
) 

use igor_bibl_db;
select DISTINCT id2 FROM (
SELECT id2 FROM OBJ_ASSOC WHERE id1 in(476036) 
UNION 
SELECT id1 FROM OBJ_ASSOC WHERE id2 in(476036) 
) AS SEL_ID


use igor_bibl_db;
SELECT DISTINCT id2   
FROM OBJ_ASSOC INNER JOIN OBJECTS ON OBJ_ASSOC.id2 = OBJECTS.id AND OBJECTS.type in (4,2) 
WHERE  id2 in ( SELECT id2 FROM OBJ_ASSOC WHERE id1 in(484209) ) 

use igor_bibl_db;
SELECT DISTINCT id2   
FROM OBJ_ASSOC INNER JOIN OBJECTS ON OBJ_ASSOC.id2 = OBJECTS.id 
WHERE  id2 in ( SELECT id2 FROM OBJ_ASSOC WHERE id1 in(484209)  )
UNION
SELECT DISTINCT id1 
FROM OBJ_ASSOC INNER JOIN OBJECTS ON OBJ_ASSOC.id1 = OBJECTS.id 
WHERE  id1 in ( SELECT id1 FROM OBJ_ASSOC WHERE id2 in(484209)  )

select * from objects where id=484209


use igor_bibl_db;
SELECT DISTINCT ID1,OBJECTS.TYPE FROM OBJ_ASSOC INNER JOIN OBJECTS ON OBJ_ASSOC.ID1 = OBJECTS.ID AND OBJ_ASSOC.TYPE = 1  
WHERE ID2 = 484209 AND OBJECTS.TYPE in (2,4)

use igor_bibl_db;
SELECT DISTINCT id2 FROM OBJ_ASSOC INNER JOIN OBJECTS ON OBJ_ASSOC.id2 = OBJECTS.id  WHERE id2 in ( SELECT id2 FROM OBJ_ASSOC WHERE id1 in(484209) ) 

# get authors by keyword query: authors on the left from keywords - that's different from hierarchy of keywords:
use igor_bibl_db;
SELECT ID1 FROM OBJ_ASSOC 
INNER JOIN OBJECTS  ON OBJ_ASSOC.ID1 = OBJECTS.ID AND OBJ_ASSOC.TYPE = 1  
WHERE ID2 = 484209 AND OBJECTS.TYPE = 2 

# get associated keywords no direction of association
SELECT DISTINCT id2 FROM OBJ_ASSOC 
#INNER JOIN OBJECTS ON OBJ_ASSOC.id2 = OBJECTS.id AND OBJECTS.type in (4,2) 
WHERE  (id2 in ( 
SELECT id2 FROM ( 
SELECT id2 FROM OBJ_ASSOC WHERE id1 in(484209) 
UNION 
SELECT id1 FROM OBJ_ASSOC WHERE id2 in(484209)
) AS ID_NDIR  )) 


# get associated objects - no direction:
SELECT DISTINCT id FROM OBJECTS 
#INNER JOIN OBJECTS ON OBJ_ASSOC.id2 = OBJECTS.id AND OBJECTS.type in (4,2) 
WHERE  (id in ( 
SELECT id2 FROM ( 
SELECT id2 FROM OBJ_ASSOC WHERE id1 in(484209) 
UNION 
SELECT id1 FROM OBJ_ASSOC WHERE id2 in(484209)
) AS ID_NDIR  )) 




