SELECT * FROM REFS WHERE REF_ID = 707495;
SELECT * FROM AUTHORS WHERE AUTH_ID = 707754; --  
SELECT * FROM AUTHORS WHERE AUTH_ID = 655583; -- NARTH
SELECT * FROM AUTHORS WHERE AUTH_ID = 402605; -- Cisneros
SELECT * FROM AUTHORS WHERE AUTH_ID = 402544; -- Ren
SELECT * FROM AUTHORS WHERE AUTH_ID = 445605; -- Lagardere
SELECT * FROM AUTHORS WHERE AUTH_ID = 707761;

SELECT AUTH_ID FROM AUTHORS WHERE LAST_NAME ="LAGARDèRE" AND INITIALS = "L";
SELECT AUTH_ID FROM AUTHORS WHERE LAST_NAME ="LAGARDERE" AND INITIALS = "L";

INSERT INTO AUTHORS (AUTH_ID,LAST_NAME,INITIALS,FIRST_NAME) VALUES(707761,"LAGARDèRE","L","LOUIS");
