# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Tue Oct  4 09:55:21 2022
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import biblpy.gs
# end wxGlade


class gs_ref_dlg_GUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: gs_ref_dlg_GUI.__init__
        # this code before gs frame
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("Google Scholar Actions")

        # Menu Bar
        self.gs_frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.gs_frame_menubar.Append(wxglade_tmp_menu, "Load Ref Info")
        wxglade_tmp_menu = wx.Menu()
        self.gs_frame_menubar.Append(wxglade_tmp_menu, "Check Reference")
        self.SetMenuBar(self.gs_frame_menubar)
        # Menu Bar end

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.btn_test_1 = wx.Button(self.panel_1, wx.ID_ANY, "Test1")
        sizer_1.Add(self.btn_test_1, 0, 0, 0)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "button_2")
        sizer_1.Add(self.button_2, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        self.button_3 = wx.Button(self.panel_1, wx.ID_ANY, "button_3")
        sizer_2.Add(self.button_3, 0, 0, 0)

        self.button_4 = wx.Button(self.panel_1, wx.ID_ANY, "button_4")
        sizer_2.Add(self.button_4, 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # this code after gs frame

        self.btn_test_1.Bind(wx.EVT_BUTTON, self.OnTest1)
        # end wxGlade

    def OnLoadRefInfo(self, event):  # wxGlade: gs_ref_dlg_GUI.<event_handler>
        print("Event handler 'OnLoadRefInfo' not implemented!")
        event.Skip()

    def OnCheckRef(self, event):  # wxGlade: gs_ref_dlg_GUI.<event_handler>
        print("Event handler 'OnCheckRef' not implemented!")
        event.Skip()

    def OnTest1(self, event):  # wxGlade: gs_ref_dlg_GUI.<event_handler>
        print("Event handler 'OnTest1' not implemented!")
        event.Skip()

# end of class gs_ref_dlg_GUI
